### PR TITLE
feat: unblock scroll on next renderer blocks

### PR DESCRIPTION
**Pull request by skokenes**
When scrolling in Malloy notebook, if you scroll on a table that has room to scroll, it will scroll the table instead of the notebook. Otherwise, it keeps scrolling the notebook

### CODE REVIEW

**Review by whscullin — COMMENTED** [review]
I'm seeing this get confused if there are multiple outputs. If a table has a scroll bar and is blocking scrolling in one direction, then all tables will block scrolling. I'm not exactly sure what's going, nothing is jumping out at me.

**Comment by skokenes** [comment]
Ah darn, I had also noticed some weird behavior when I first implemented it but then I couldn't reproduce it so I thought it was a fluke. I will take another look. If you have steps to reproduce, please share

**Comment by whscullin** [comment]
I was using https://github.com/malloydata/malloy-samples/blob/main/names/names1.malloynb, if you set it to use renderer_next the first few results have no scroll bar, and work fine. Once I hit "Compare 'Linda' and 'Elizabeth' over decades", which has a scroll bar, that's when things break. Looking again, I think you may need to move `mousewheelHandler()` inside `renderOutputItem()`, because otherwise `shadow`'s scope is too broad.

**Comment by whscullin** [comment]
Apparently there needs to be a fudge factor in detecting scroll bottom, I'm hitting this:
```
$0.clientHeight
600
$0.scrollHeight
701
$0.scrollTop
100.83332824707031
```
700.83332824707031 < 701 so `isAtBottom` is `false` , and it won't scroll further  😐.

**Comment by whscullin** [comment]
Obsolete

**Pull request closed without merging**
