### PR TITLE
feat: embed new renderer

### PR DESCRIPTION
**Pull request by skokenes**
Adds support for turning on new renderer in VS Code preview and notebooks with model tag:
- some CSS changes to ensure overflow is handled properly with new renderer table scrolling
- Our default font Inter is loaded from a CDN
- malloy packages bumped to latest release
- scrolling on new renderer output cell in notebook stops propagation to not trigger notebook scroll

Note: this PR does not handle theming the new renderer based on the current VS Code theme. That is TBD

All of the old renderer functionality should stay the same. New renderer is only visible by adding the model tag `## renderer_next` in malloy scripts

### CODE REVIEW

**Review by whscullin — APPROVED** [review]
LGTM

**Comment by whscullin** [comment]
A nice thing to have would be that if you're scrolled all the way to the top, or all the way to the bottom, of the results page, scroll passes back to the parent.

**Comment by whscullin** [comment]
There was a lot of seemingly random changes in your package-lock.json, re-did the update and pushed a version with only the intended changes.

**Comment by skokenes** [comment]
> A nice thing to have would be that if you're scrolled all the way to the top, or all the way to the bottom, of the results page, scroll passes back to the parent. Right now, particularly if the results are 100% tall, scrolling in the result page is just a no-op, which feels odd.

Agreed, I actually took a stab at that today as part of this PR but hit some hurdles so I punted on it. I can look into it tomorrow as a fast follow.

Thanks for fixing the package-lock.json, not sure what happened there.

**Pull request merged**
