### PR TITLE
Support hiding fields

### PR DESCRIPTION
**Pull request by whscullin**
Add a `hidden` tag that takes an array of values that can either be string literals or RegExps,

Without `hidden`:
Screenshot 2023-12-08 at 3 04 43 PM

With `hidden`
Screenshot 2023-12-08 at 3 05 03 PM

### CODE REVIEW

**Comment by whscullin** [comment]
(Also includes some unused variable cleanup)

**Comment by narreola** [comment]
-Hidden tag is already implemented at renderer level, to hide fields. It hides the tagged element. It feels to me that the same keyword works slightly different. Could we use a different word? Maybe hide?
-Should we move this logic to a common place? If you are using the hidden tag here, should it also hide the fields for the renderer?

**Comment by lloydtabb** [comment]
> -Hidden tag is already implemented at renderer level, to hide fields. It hides the tagged element. It feels to me that the same keyword works slightly different. Could we use a different word? Maybe hide? -Should we move this logic to a common place? If you are using the hidden tag here, should it also hide the fields for the renderer?

Interesting.  I think we are ok.  There is a difference between a source and a result.  Hidden on a dimension/measure means don't show it in options of fields to pick.  Hidden on a group_by, aggregate or select means don't show it in the result (the renderer).

**Comment by whscullin** [comment]
Yeah, `deleted` is a boolean field name (third from left in top image)

**Pull request merged**
