### PR TITLE
Prevent SQL highlighting from being applied in Malloy-in-SQL block

### PR DESCRIPTION
**Pull request by ksittner**
In order to address #199 and update syntax highlighting to reflect changes to the grammar, the following changes are included:
1. Prevent SQL highlighting from being applied in Malloy-in-SQL block
2. Update dates, timestamps, and numbers per [docs](https://malloydata.github.io/documentation/language/datatypes.html) and our [ANTLR grammar](https://github.com/malloydata/malloy/blob/main/packages/malloy/src/lang/grammar/MalloyLexer.g4)
3. Update unquoted identifiers and string escapes per our ANTLR gramar

### CODE REVIEW

**Comment by christopherswenson** [comment]
This all looks really good. The only thing I noticed is:

* `@2001-02-03 04:05:06.001[America/Mexico_City]` is a valid timestamp in Malloy, but does not syntax highlight with the `[America/Mexico_City]` included in the highlight. 

Also, this is not something that is wrong with your PR, but we may want to give some extra consideration to `"""` strings. Previously they were only ever for SQL, but now you can use them anywhere where you need a string. We probably want the `"""`s to be highlighted red like other strings, and maybe we want to intelligently highlight as SQL or a regular string depending on whether it is in a `connection_name.sql("""` or `select: """` or somewhere else.

**Comment by ksittner** [comment]
Thank you for pointing out the issue with triple quote strings! I've handled that in our other grammar but not here for some reason. 

As far as the timestamp `@2001-02-03 04:05:06.001[America/Mexico_City]`, I do notice that generic bracket highlighting is being applied to `[` and `]`, but on my end proper syntax highlighting is being applied to the `America/Mexico_City` portion as well. It appears to be a limitation of the VSCode language configuration, which is also used in the Monaco editor, that the default bracket styling, resulting from how we set `brackets` in  `malloy-language.json`, can only be overridden by top-level tokenization rules. I'll reach out to you to discuss potential resolutions.

**Comment by ksittner** [comment]
> `@2001-02-03 04:05:06.001[America/Mexico_City]` is a valid timestamp in Malloy, but does not syntax highlight with the `[America/Mexico_City]` included in the highlight.

Is the `America/Mexico_City` part not receiving any styling at all for you or is it partially receiving our default identifier styling?

**Review by christopherswenson — APPROVED** [review]
Looks great! 🚢 🇮🇹

**Pull request merged**
