### PR TITLE
Consolidate worker functionalities onto LSP server(2nd try)

### LINKED ISSUE #131: Canceling a running query kills extension
Pressing cancel when running a query consistently kills extension for me, resulting in all future queries erroring like: 

Screenshot 2023-05-06 at 6 05 21 PM

Reproduce using a longer-ish running query - press Run Query then press Cancel in progress bar in lower right. [This query](https://github.com/malloydata/malloy-samples/blob/main/bigquery/faa/flights.malloy#L57) lets me do it consistently. Exception is:

```
Exception has occurred: Error: Request malloy/queryPanel failed with message: Webview is disposed
  at handleResponse (/Users/bporterfield/dev/malloydata/malloy-vscode-extension/dist/server_node.js:2100:40)
    at processMessageQueue (/Users/bporterfield/dev/malloydata/malloy-vscode-extension/dist/server_node.js:1938:13)
    at Immediate._onImmediate (/Users/bporterfield/dev/malloydata/malloy-vscode-extension/dist/server_node.js:1924:11)
    at process.processImmediate (node:internal/timers:466:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

Appears to be related to recent change to combine worker and server, trying a build from before that merge did not reproduce the error.

### PR DESCRIPTION
**Pull request by caleb-c-li**
This is a second try of consolidating worker functionality onto LSP server. The patch is mostly identical to the commit 87b9739 with the following changes.
- found a typo in the first try that `sendRequest('malloy/cancel', panelId)`  should be `sendRequest('malloy/cancel', {type: 'malloy/cancel', panelId: panelId,})`. Tweaked the corresponding part in `msql_utils.ts` as well.
- the original cancellation handling works in the following way: On a cancel, the `run_query_utils.ts` invokes `current.panel.dispose()`, which issues a cancel request to the worker. On the worker side, the workflow simply returns without sending anything back. Now this functionality is moved to the LSP server. It should continue to work as long as the `panelId` is passed down correctly. 
- upgraded the `vscode-languageclient` and `vscode-languageserver` to 8.1.0. The recovery capability of LSP language server is improved that the 'Unhandled method' error is not shown when server crashes/restarts.

Fixes #131

### CODE REVIEW

**Review by bporterfield — CHANGES_REQUESTED** [review]
When I try this branch, pressing cancel makes the progress dialog disappear but does not seem to make the new tab disappear - it still says there with "Running" and the spinner. At some point a bit later the tab disappears, but it feels to slow to be a good experience?

Also, with enough pressing "cancel", closing the query panel tab before it gets closed on its own, and re-running the same query, I'm pretty consistently still hitting "Unhandled method malloy/fetch"

**Comment by caleb-c-li** [comment]
> This LGTM to prevent the restart. I wonder, though, in the event that the language server is being restarted, are we not hooking the message handlers back up correctly?

Is the question regarding 'malloy/fetch' message handler? It's originally part of worker connection, then it is moved to LSP client. I don't have a theory on why the `Unhandled method malloy/fetch` error is shown whenever the LSP server restarted. Is it because only the server is restarted not the client?

**Comment by whscullin** [comment]
We may want to put more time into investigating how canceling is handled, and making sure the server is restarting properly when it crashes. https://github.com/malloydata/malloy-vscode-extension/pull/135 is a revert for the worker/language server merger should we chose to go that route.

**Comment by caleb-c-li** [comment]
> When I try this branch, pressing cancel makes the progress dialog disappear but does not seem to make the new tab disappear - it still says there with "Running" and the spinner. At some point a bit later the tab disappears, but it feels to slow to be a good experience?
> 
> Also, with enough pressing "cancel", closing the query panel tab before it gets closed on its own, and re-running the same query, I'm pretty consistently still hitting "Unhandled method malloy/fetch"

The cancellation is not preemptive, the query may already start running when a `Cancel` request is issued. Malloy will let the run finish but not return the results. Then original implementation dispose the web view right away so it feels more responsive.

If the query panel is closed when the query is running, it will cause a restart in the LSP server if the client was allowed to talk to the server directly (#129).

**Comment by bporterfield** [comment]
Some queries may take many minutes, so we need to close the query panel when the user hits the cancel button in the progress bar, like in the prior implementation. If there is a lag, it's confusing for the user - the user will need to press cancel and also close the query panel tab that will just sit there for no good reason. The prior experience was optimal, we should try to make that possible with this implementation unless for some reason it's impossible.

**Comment by caleb-c-li** [comment]
> Some queries may take many minutes, so we need to close the query panel when the user hits the cancel button in the progress bar, like in the prior implementation. If there is a lag, it's confusing for the user - the user will need to press cancel and also close the query panel tab that will just sit there for no good reason. The prior experience was optimal, we should try to make that possible with this implementation unless for some reason it's impossible.

The root-cause appears to be a copy-paste error. I've updated the patch description. PTAL.

**Comment by bporterfield** [comment]
This feels strange to me:

```
client.sendRequest('malloy/run-msql', {
        type: 'malloy/run-msql',
```

I'd imagine it's not necessary to have both the message name and a duplicate type?

**Comment by caleb-c-li** [comment]
> This feels strange to me:
> 
> ```
> client.sendRequest('malloy/run-msql', {
>         type: 'malloy/run-msql',
> ```
> 
> I'd imagine it's not necessary to have both the message name and a duplicate type?

Yes, it feels duplicated. The message type is actually used in a few different places such as:

```
      return new Promise(resolve => {
        let off: vscode.Disposable | null = null;
        const listener = (msg: WorkerMessage) => {
          if (msg.type !== 'malloy/MSQLQueryPanel') {
            return;
          }
          const {message, panelId: msgPanelId} = msg;
```

I would prefer log a different Github issue and address them separately. Further cleaning them up may require more thinking.

**Comment by bporterfield** [comment]
Screenshot 2023-05-09 at 3 14 17 PM

Don't think we're quite there - it looks I can still get the extension into this state. I run a long-running query, and press "Run Query" on the same query before the first one completes.

Generally, it looks as though after the server restarts, things remain broken forever. We should solve this double-run-query thing, but also it seems like we need a solution for the general case to re-hook things after a server restart? @whscullin mentioned that [up here](https://github.com/malloydata/malloy-vscode-extension/pull/134#pullrequestreview-1417433291)

**Comment by caleb-c-li** [comment]
> it looks I can still get the extension into this state. I run a long-running query, and press "Run Query" on the same query before the first one completes.

I've tried the HEAD version with the worker arch. Looks like it can also easily get into an unavailable state if one presses "Run Query" repeatedly.

Screenshot 2023-05-10 at 9 38 13 AM


> Generally, it looks as though after the server restarts, things remain broken forever. We should solve this double-run-query thing, but also it seems like we need a solution for the general case to re-hook things after a server restart? @whscullin mentioned that https://github.com/malloydata/malloy-vscode-extension/pull/134#pullrequestreview-1417433291

Yes, Discussed separately. Will suggests looking into a newer version of LSP language server packages that might have this functionality. Investigating it now...

**Comment by caleb-c-li** [comment]
Upgraded the vscode-languageserver and vscode-languageclient to 8.1.0. The "Unhandled method xyz" error goes away. PTAL.

**Pull request merged**
